### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by iuscare** [studiometa/js-toolkit#108]
Hey there,

love to see the current work flowing into this. Is there any typescript support already built in? I recognized the jsdoc type declarations and the node_modules folder also shows .d.ts files after installing the package. However I got linting issues as soon as I try to work with the refs object, e.g. `this.$refs.toggler.addEventListener('click', this.toggle);` leads to `<html>TS2339: Property 'addEventListener' does not exist on type 'typeof Base | HTMLElement | (typeof Base | HTMLElement)[]'.<br/>Property 'addEventListener' does not exist on type 'typeof Base'.`

**Comment by iuscare** [comment]
Closed, because after `declare module '@studiometa/js-toolkit';` typescript recognizes the types.

**Comment by titouanmathis** [comment]
Hey @iuscare, thanks for the report, let me add some info on how you can add types to your components 🙂 

A ref can indeed be one of the listed type from the message you got, but the `$refs` object is generated dynamically based on the `Class.config.refs` values, we can not define the type automatically. You can however define a custom interface for your component and use the `this` parameter (see [TypeScript doc](https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function)).

```ts
import Base from '@studiometa/js-toolkit';

interface ComponentInterface extends Component {
  $refs: {
    btn: HTMLElement;
    items: HTMLElement[],
  },
  $options: {
    classes: string[];
  }
}

export default class Component extends Base {
  static config = {
    name: 'Component',
    refs: [ 'btn', 'items[]' ],
    options: {
      classes: Array,
    },
  };

  mounted(this: ComponentInterface) {
    // Should autocomplete to `this.$refs.btn` or `this.$refs.items`
    this.$refs
  }
}
```

![Capture d’écran 2021-05-30 à 12 54 18](https://user-images.githubusercontent.com/250145/120101387-2c4c4700-c146-11eb-95b7-217140c5b390.png)
![Capture d’écran 2021-05-30 à 12 55 16](https://user-images.githubusercontent.com/250145/120101424-4ede6000-c146-11eb-8fba-0e3e14b4c9c7.png)

As we do not use TypeScript in our project, we do the same with JSDocs comments:

```js
import Base from '@studiometa/js-toolkit';

/**
 * @typedef {Object} ComponentRefs
 * @property {HTMLElement} btn
 * @property {HTMLElement[]} items
 */

/**
 * @typedef {Object} ComponentOptions
 * @property {string[]} classes
 */

/**
 * @typedef {Object} ComponentInterface
 * @property {ComponentRefs} $refs
 * @property {ComponentOptions} $options
 */

/**
 * Component class.
 */
export default class Component extends Base {
  static config = {
    name: 'Component',
    refs: ['btn', 'items[]'],
    options: {
      classes: Array,
    },
  };

  /**
   * @this {Component & ComponentInterface}
   */
  mounted() {
    // Should autocomplete to `this.$refs.btn` or `this.$refs.items`
    this.$refs
  }
}
```

---

On a side note, and if you did not find it in the doc, you should know that you can bind a method to a ref event by following the `on<RefName><EventName>` pattern:

```ts
interface ComponentInterface extends Component {
  $refs: {
    toggle: HTMLElement,
    items: HTMLElement[],
  }
}

export default class Component extends Base {
  static config = {
    name: 'Component',
    refs: ['toggle', 'items[]'],
  };

  onToggleClick(event: MouseEvent) {
    event.preventDefault();
  }

  onItemsClick(this: ComponentInterface, event: MouseEvent, index: number) {
    this.$refs.items[index].style.display = 'none';
  }
}
```

**Comment by iuscare** [comment]
Thanks for your effort in this in depth view how typescript can properly work with the framework. I really appreciate it. I checked your source and saw those jsdoc comments. I guess the types are being generated during the production build out of these jsdoc statements. I am in an ongiong process to switch/rewrite a whole custom written javascript library with your toolkit. It's been a breeze so far. Can sort out so many things, because they are simply included in your library. Guess will stick with it for upcoming projects 😊
