### ISSUE TITLE
BreakpointManager breaks on safari with custom webpack build

### ISSUE THREAD

**Issue by iuscare** [studiometa/js-toolkit#121]
Hey there, I am using tailwind with jit and therefore I copied over your breakpoints plugin and required it in my tailwindconfig. The BreakpointManager works well on all browser except on Safari. When replicating your BreakpointManagerDemo, I get following error, even tough I defined my breakpoints and also added the `data-breakpoint` attribute to the DOM.

```
Error: The `BreakpointManager` class requires breakpoints to be defined.
```

Strangely, when I am using a dynamic import for the component, the BreakpointManager also works on Safari:
```
import Base from '@studiometa/js-toolkit';
import { $body } from './utils';

class App extends Base {
  static config = {
    name: 'App',
    components: {
      // This works, as long as I am using a dynamic import
      BreakpointManagerDemo: () => import( /* webpackChunkName: "BreakpointManagerDemo" */ './components/BreakpointManagerDemo')
    },
  };
}

const app = new App($body);
app.$mount();

export default app;

// Accept HMR as per: https://webpack.js.org/api/hot-module-replacement#accept
if (module.hot) {
  module.hot.accept();
}
```

So it seems that something is messing up the initialization. I know that this might not be a real bug, but rather could rely on my webpack config. But I would be very thankful if someone have an idea or hint, how to solve the issue.

**Comment by titouanmathis** [comment]
Hey @iuscare,

The breakpoints are read from the `::before` and `::after` pseudo-elements on the `[data-breakpoint]` element. Could you check that they are indeed there? The error you encountered is thrown when these pseudo-elements could not be found or read.

**Comment by iuscare** [comment]
Hey @titouanmathis, thanks for your input. I will check that today and tomorrow and will come back with what I've found out.

**Comment by iuscare** [comment]
So it turns out, that no pseudo element is being added on the [data-breakpoint] attribute, indeed. This only happens on safari, and I don't know why yet.

**Comment by iuscare** [comment]
So I looked a little bit further down the road, and just want to document what I've found out so far:

- If I dont use a `withBreakpointManager` component, the `content` of the [data-breakpoint] attribute gets added the right way
- If I use a `withBreakpointManager` component, no content seems to be added to the [data-breakpoint] attribute - only on safari
- Through debugging it seems that `this.breakpoint` exists https://github.com/studiometa/js-toolkit/blob/bcd79fcbd2a89d3c7009fb4cb51605d5e0d36c58/packages/js-toolkit/services/resize.js#L110
- But the following `.getPropertyValue('content')` returns nothing https://github.com/studiometa/js-toolkit/blob/bcd79fcbd2a89d3c7009fb4cb51605d5e0d36c58/packages/js-toolkit/services/resize.js#L117-L122
- Therefore `props().breakpoint` returns also nothing leading to the error below https://github.com/studiometa/js-toolkit/blob/bcd79fcbd2a89d3c7009fb4cb51605d5e0d36c58/packages/js-toolkit/decorators/withBreakpointManager.js#L61-L65
- The issue with the `.getPropertyValue('content)' happens on all of my browsers, but it seems that firefox/chrome updates the breakpoint somehow afterwards, whereas the js in safari crashes
- Sadly only happens on my project, whereas the same debugging methods in your demo do not lead to the described behavior above

**Comment by iuscare** [comment]
Somehow this seems happily to be fixed in one of your last updates, since the error disappeared without any further modifications on my end 👏

Happy Christmas to studiometa! 🎄
