### ISSUE TITLE
Intersection decorator used within the lazy demo component breaks on safari

### ISSUE THREAD

**Issue by iuscare** [studiometa/js-toolkit#146]
Hey there, the intersection decorator used within the lazy demo component does not seem to work properly on safari. I get the following error with the example of your docs

```
TypeError: window.requestIdleCallback is not a function. (In 'window.requestIdleCallback(this.load)', 'window.requestIdleCallback' is undefined)
```

This also happens on your demo page with the lazyload image component [here](https://studiometa-js-toolkit-demo.netlify.app/). The IDE complains about `TS2339: Property 'requestIdleCallback' does not exist on type 'Window & typeof globalThis'.` Maybe this helps.

All the best

**Comment by titouanmathis** [comment]
This should be fixed in the beta versions of the v2, as `requestIdleCallback` usages are conditioned by the function support.
