### ISSUE TITLE
Add a utility function to get a random number

### ISSUE THREAD

**Issue by perruche** [studiometa/js-toolkit#202]
Add a utility function to get a random number between a given minimum and maximum value.

```
/**
   * Get a random number between bounds
   *
   * @param {number} min minimum value
   * @param {number} max maximum value
   * @returns {number}
   */
  getRandomNumber(min = 0, max = 3) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }
```

**Comment by titouanmathis** [comment]
We could also add a function to get a random index between `0` and a length:

```js
function getRandomIndex(length) {
  return getRandomNumber(0, length);
}
```

**Comment by antoine4livre** [comment]
@perruche @titouanmathis I prefer `getRandomInt` instead of `getRandomNumber`, is that okay for you ?

Maybe can I suggest a `getRandomItem` to get a random item of an Array ?

**Comment by titouanmathis** [comment]
Yes and yes 👍

**Comment by antoine4livre** [comment]
@titouanmathis I suggest to invert `min` and `max` parameters to have a shorthand to get a random int from 0 to the defined max without specifying the min:

```js
getRandomInt(5); // get a random int between 0 and 5
getRandomInt(5, 2); // get a random int between 2 and 5
```

With that we don't need the `getRandomIndex` util.
