### ISSUE TITLE
Compatibility issue for ResizeObserver in Safari

### ISSUE THREAD

**Issue by perruche** [studiometa/js-toolkit#28]
## Compatibility issue for ResizeObserver in Safari < 13.1
`ReferenceError: Can't find variable: ResizeObserver`

https://caniuse.com/#feat=resizeobserver

This bug was introduce in alpha.11 version which is using `new ResizeObserver()` to handle resize in src/services/resize.js by using.

Should add a polyfill to support at least the last 2 versions of each main browser ?

**Comment by titouanmathis** [comment]
Thanks for the report, it has been fixed in [v1.0.0-alpha.12](https://github.com/studiometa/js-toolkit/releases/tag/1.0.0-alpha.12) 🎉
