### ISSUE TITLE
FR: Data Attribute as Callback Functions?

### ISSUE THREAD

**Issue by iuscare** [studiometa/js-toolkit#401]
Hi there,
I'm currently working a bit with AJAX and was wondering if it's possible to attach callback functions as data attributes. I tried it with data-option-callback='callBackFunction', but it seems that this.$options only allow primitives, such as strings or numbers, or am I seeing this wrong? The callback is important for me at this point because I animate the inserted content after successful loading with GSAP, and therefore need to inject JS. But there are surely also some other use cases where such callback functions would be interesting. Is this idea a good extension to the framework?

Here's an example using options, which currently doesn't seem to be functioning properly. Additionally, it's worth noting that even if it did work, there would likely be issues when multiple AjaxLoad components are present on the same page. In such a scenario, implementing some form of context awareness would probably be necessary
```html
<div 
  data-component="AjaxLoad" 
  data-option-src="url-to-fetch" 
  data-option-callback="callBackFunction"
>
   <div data-ref="loading">Loading...</div>
   <div data-ref="error" style="display: none;">An error occurred.</div>
</div>
```

```ts
// AjaxLoad.js
import { Base } from '@studiometa/js-toolkit';
import type { BaseProps } from '@studiometa/js-toolkit';

export interface AjaxLoadProps extends BaseProps {
  $refs: {
    loading: HTMLElement;
    error: HTMLElement;
  };
  $options: {
    src: string;
    terminateOnLoad: boolean;
    callback?: (content: string, element: HTMLElement) => void;
  };
}

/**
 * AjaxLoad class.
 */
export class AjaxLoad extends Base<AjaxLoadProps> {
  /**
   * Config.
   */
  static config = {
    name: 'AjaxLoad',
    refs: ['loading', 'error'],
    options: {
      src: String,
      terminateOnLoad: Boolean,
      callback: Function,
    },
  };

  /**
   * Load the content on mount using async/await.
   */
  async mounted() {
    if (!this.$options.src) {
      this.$log('The `src` option is missing.');
      return;
    }

    try {
      const response = await fetch(this.$options.src, {
        headers: { 'X-Requested-With': 'XMLHttpRequest' },
        method: 'GET',
      });

      if (!response.ok) {
        throw new Error('Network response was not ok');
      }

      const content = await response.text();
      this.handleContentLoaded(content);
    } catch (error) {
      this.handleError(error);
    } finally {
      this.finalizeLoading();
    }
  }

  /**
   * Handle loaded content and execute callback if provided.
   */
  handleContentLoaded(content: string) {
    this.$refs.loading.style.display = 'none';
    this.$el.innerHTML = content;

    if (typeof this.$options.callback === 'function') {
      this.$options.callback(content, this.$el);
    }
  }

  /**
   * Handle error.
   */
  handleError(error: any) {
    this.$log(error);
    this.$refs.error.style.display = 'block';
  }

  /**
   * Finalize loading process.
   */
  finalizeLoading() {
    if (this.$options.terminateOnLoad) {
      this.$terminate();
    }
  }
}
```

**Comment by titouanmathis** [comment]
Hey @iuscare, thanks for the feedback and suggestion!

Allowing functions as options would need some extra care to parse and evaluate the function, as this could introduce security issues. I am not sure we will have time to implement it in the near future, as this is a feature we do not need for our own development. But I will keep it in mind!

For your use case, I would suggest defining the callbacks that you need in an object with keys that could be used as reference in the `data-option-callback` attribute. 

```html
<div data-component="AjaxLoad" data-option-callback="myCustomCallback">
  ...
</div>
```

```ts
import { Base } from '@studiometa/js-toolkit';
import { isFunction } from '@studiometa/js-toolkit/utils';
import gsap from 'gsap';

const callbacks = {
  myCustomCallback(content, el) {
    gsap.to(el, 1, { opacity: 1 });
  },
};

export default class AjaxLoad extends Base {

  // ...

  handleContentLoaded(content: string) {
    this.$refs.loading.style.display = 'none';
    this.$el.innerHTML = content;

    const callback = callbacks[this.$options.callback]

    if (isFunction(callback)) {
      callback(content, this.$el);
    }
  }
}
```

Another option would be to extend the AjaxLoad class as many times as custom callbacks you need: 

```ts
import AjaxLoad from './AjaxLoad.js';

export class AjaxLoadFadeIn extends AjaxLoad {
  handleContentLoaded(content: string) {
    super.handleContentLoaded(content);

    gsap.to(this.$el, 1, { opacity: 1 });
  }
}

export class AjaxLoadSlideIn extends AjaxLoad {
  handleContentLoaded(content: string) {
    super.handleContentLoaded(content);

    gsap.from(this.$el, 1, { y: 100 });
  }
}
```

A third option would be to use options to configure the gsap parameters you want: 

```ts
import { Base } from '@studiometa/js-toolkit';
import { isFunction } from '@studiometa/js-toolkit/utils';
import gsap from 'gsap';

export default class AjaxLoad extends Base {

  static config = {
    name: 'AjaxLoad',
    options: {
      duration: { type: Number, default: 1 },
      from: { type: Object, default: () => ({ opacity: 0 }) },
      to: { type: Object, default: () => ({ opacity: 1 }) },
    },
  };

  handleContentLoaded(content: string) {
    this.$refs.loading.style.display = 'none';
    this.$el.innerHTML = content;

    gsap.fromTo(
      this.$el, 
      this.$options.duration, 
      this.$options.from, 
      this.$options.to
    );
  }
}
```

We used a similar approach to create our [`ScrollAnimation` component](https://ui.studiometa.dev/-/components/atoms/ScrollAnimation/examples.html), it works quite well.

Or you could implement a component similar to our [`Frame` component](https://ui.studiometa.dev/-/components/organisms/Frame/examples.html), which is itself based on our [`Transition` component](https://ui.studiometa.dev/-/components/primitives/Transition/).

**Comment by titouanmathis** [comment]
Hey @iuscare,

Just to let you know that we have added an [`Action` component](https://ui.studiometa.dev/-/components/atoms/Action/) to our https://github.com/studiometa/ui package that might interest you. It lets you declare methods that should be called on other component right from your HTML. 

I'll close this issue for now, but feel free to keep the discussion going.

**Comment by titouanmathis** [comment]
@iuscare I have opened a PR on our UI package, adding some components that might be of interest for you: https://github.com/studiometa/ui/pull/256.
