### ISSUE TITLE
Component seems to be resolved on html tag, too

### ISSUE THREAD

**Issue by iuscare** [studiometa/js-toolkit#403]
Hey there,

running into a strange issue, and wanted to know, if this is by design, a bug or a mistake on my end:

When defining new Components, e.g. a Figure or Button class, the toolkit seems to resolve this also on `<figure>` and `<button>` elements, even when they not have the `data-component="Figure/Button"` attached. Can you confirm this?

**Comment by titouanmathis** [comment]
This is a side effect of a design decision. When defining children components in `config.components`, the keys can either be the name of a component or a CSS selector. Components are then looked up in the following order: 

1. It tries to find any `[data-component="${name}"]` HTML element
2. If no element was found, it falls back to using `name` as a CSS selector by doing `querySelectorAll(name)` 

You can find the code for this here: https://github.com/studiometa/js-toolkit/blob/develop/packages/js-toolkit/Base/utils.ts#L59-L77

The `querySelector('Figure')` method will also match against `<figure>` elements, ignoring the case of the selector. We could add a check to avoid the fallback if the selector is not in lowercase.
