### ISSUE TITLE
How can I use it with a template engine via script tag?

### ISSUE THREAD

**Issue by hasansezertasan** [studiometa/js-toolkit#409]
Well. I'm quite interested in your work. I'm a backend developer and mostly using template engines such as Jinja2, EJS, etc.

So I don't want to mess with NPM and JSX. How can I use it with a template engine via script tag?

**Comment by titouanmathis** [comment]
Hey @hasansezertasan, thanks for the interest! 

We currently use a bundler for our own usage, but you can also use the framework via script tag, here is a demo: https://65cba3f0e057de0fa97f933a--bright-croquembouche-4ecc45.netlify.app/

The HTML for this demo is the following:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Demo</title>
    <script type="importmap">
      {
        "imports": {
          "@studiometa/js-toolkit/utils": "https://cdn.skypack.dev/pin/@studiometa/js-toolkit@v2.12.0-Mt2J7j9etLMlc7ZsoAC2/mode=imports,min/optimized/@studiometa/js-toolkit/utils.js",
          "@studiometa/js-toolkit": "https://cdn.skypack.dev/pin/@studiometa/js-toolkit@v2.12.0-Mt2J7j9etLMlc7ZsoAC2/mode=imports,min/optimized/@studiometa/js-toolkit.js"
        }
      }
    </script>
    <script type="module">
      // Enable usage of the `debug` option, disable it when in production
      window.__DEV__ = true;
    </script>
  </head>
  <body>
    <!-- START Foo -->
    <div data-component="Foo">
      <button type="button" data-ref="btn">Click me</button>
      <span data-ref="content">0</span>
    </div>
    <script type="module">
      import { Base } from '@studiometa/js-toolkit';

      class Foo extends Base {
        static config = {
          name: 'Foo',
          debug: true,
          refs: ['btn', 'content'],
        };

        count = 0;

        onBtnClick() {
          this.count += 1;
          this.$refs.content.textContent = this.count;
        }
      }

      window.Foo = Foo;
    </script>
    <!-- END Foo -->

    <pre data-ref="pointer"></pre>

    <script type="module">
      import { Base, createApp } from '@studiometa/js-toolkit';

      class App extends Base {
        static config = {
          name: 'App',
          debug: true,
          refs: ['pointer'],
          components: {
            Foo, // reference to window.Foo declared line 43
          }
        };

        moved(props) {
          this.$refs.pointer.textContent = JSON.stringify(props, null, 2);
        }
      }

      window.app = createApp(App);
    </script>
  </body>
</html>
```

**Comment by hasansezertasan** [comment]
> Hey @hasansezertasan, thanks for the interest!

Loving it 😍!

I'm sort of a Vanilla JS person (at best) so being able to use it without a NodeJS environment (and being forced to bundle it) is quite awesome. I'll dig into it more!

Also, I would love to be able to use it without initializing any "app" instance (HTMX could be an inspiration for that) but IDK if it's possible for this great project!

Thank you, I'm closing it for now! 🙏 ✔️.

**Comment by titouanmathis** [comment]
You can definitely use it without an `app` instance, you can use the static `$factory(name)` method. See lines 19 and 32 of the JS editor in this [demo](https://ui.studiometa.dev/-/play/#html=eNpNj8EOgjAQRM%2F0Kza9b6jGI3Ax8ezdeICyIBHapiyKf29LjXrcyezMvKIdHtDWXKO2k7OGDJfyZK0EPdbzXMpupBX62uEBBqZpRh0s5GHCnZKVyIpmYbYGRJbxy1Ep0y2jsOV66oLISfmEOtxD02MzLoQHpYBpZXzeQgF4u5iW2hidHcdB32Gi0JKn2FjoPKXFW7K2YY5hWV3CalRXUEUeHJUo8oBWCfHz%2FxGe7RApvpSJJn2%2BAQdHVrc%3D&style=eNoDAAAAAAE%3D&style-editor=false&script=eNqVUE1LAzEQvedXzGEhLa5b9dhSkBYEPajgsRSa7mZrbDZTklmxlP3vzibr50U8hCQz896b90xzQE9wgoUKGjqoPTYgrwO1lcFGk5q8hHNCtHtDciZEaVUIcIMI%2Bo20q0ICngRAIEWmhBJdbXYwjzUApxo9BckImcdCpbftbgrkW50KXtdhCiu5JSdzkIxnYpLrvtuxJDBl64gZL%2BIP3YLc0ppyPxoPIvRsQpGmzuZwOfsqZj07tyJnQbz0Mr2ZbrPKTmnIVN0ahk%2Bk6TY9Ryc6ISYTuHWGQFkLxrFJV%2BoAWPchCD5FVquS0B9H0eT4M6RHNKzk%2FxnUgIphJfcNvupqdPB4CD%2F8Ztr%2BMnT39HBfBPLG7Ux9TJAcXGttDle82F%2BOBm0x3N%2BcfWw1nr0Drtuwzg%3D%3D&theme=light&layout=right) for an example.
