### ISSUE TITLE
Passing variables/instances between methods

### ISSUE THREAD

**Issue by iuscare** [studiometa/js-toolkit#85]
Hi there, lately I found your toolkit, which matches my current stack in many ways and therefore, would be a good fit. Playing around with it a little, I am wondering if I get things right. Currently I often define variables or props within my constructor. Your framework provides the `config.options` object for this purpose, but does not accept instances from third party libraries, e.g. gsap. So given the example, that I'd need access to a greensock timeline within all functions of a component to revert or modify it, I thought I could do it this way:

```
import Base from '@studiometa/js-toolkit';
import { gsap } from 'gsap';

export default class Button extends Base {
  static config = {
    name: 'Button',
    refs: ['inner1', 'inner2', 'inner3', 'inner4', 'inner5'],
    log: true,
    debug: true
  };

  constructor(element: HTMLElement) {
    super(element);
    
    this.$el = element;
    this.$tl = gsap.timeline({paused: true})
  }

  mounted() {
    console.log('Now I am able to use' + this.$tl + 'everywhere in this component');
  }
}
```

Although this seems to work, it feels a little bit verboose, because I end up using config.options and the constructor, which literally are doing similar things. So I am wondering, if there is a better way to handle such use cases or if I missed something?

Thanks in advance and keep up the great work.

**Comment by titouanmathis** [comment]
Hello @iuscare, thanks for your feedback! 

We usually declare properties directly on the class and instantiate their value in the `mounted` hook:

```js
import Base from "https://cdn.skypack.dev/@studiometa/js-toolkit";
import { gsap } from "https://cdn.skypack.dev/gsap";

export default class Button extends Base {
  static config = {
    name: "Button",
    refs: ["inner1", "inner2", "inner3", "inner4", "inner5"],
    log: true,
    debug: true
  };

  /**
   * Gsap timeline.
   * @type {Timeline}
   */
  tl;

  mounted() {
    this.tl = gsap.timeline({ paused: true });
    console.log(
      "Now I am able to use" + this.tl + "everywhere in this component"
    );
  }
}
```

As the mounted hook will always be called before any other hook, `this.tl` will be available in all the other hooks.

The `config.options` should be used for per instance configuration, for example adjusting a delay with a `data-option-delay` attribute, or passing a configuration object for a third party library:

```js
export default class Button extends Base {
  static config = {
    name: "Button",
    options: {
      timeline: { type: Object, default: () => ({ paused: true }) },
    }
  };

  /**
   * Gsap timeline.
   * @type {Timeline}
   */
  tl;

  mounted() {
    this.tl = gsap.timeline({ paused: true });
  }
}
```
```html
<button data-component="Button" data-option-timeline='{ "paused": false }'>...</button>
```

On a side note, I would recommend to not use the `$` prefix as they are used to identify the internal properties and methods of the Base class. 

Let me know if things are more clear for you 😉

**Comment by iuscare** [comment]
@titouanmathis ah, I should have checked your cursor component before. It illustrates this perfectly. Thanks for the hints and explanation. I am going to use it exact the same way and I am looking forward to it. Your tool kit has incredible features by providing a consistent API, the decorators in connection with your tailwind plugins, the freedom to use dynamic imports and its utility classes. Saves a lot of time and external deps. Thanks for sharing this with the community. Really appreciate your work. 😊
