### ISSUE TITLE
v. 1.1.0 disables debug mode

### ISSUE THREAD

**Issue by iuscare** [studiometa/js-toolkit#90]
Hey there,

I just recognized that `debug: true` stops working as expected after updating to version `1.1.0`, although `process.NODE_ENV` is set to `development` on my end. The console doesn't output anything. Reverting back to `1.0.4` fixes this. Anything else seems to work on version `1.1.0`. If I can assist anything further in debugging please let me know.

Cheers & have a nice weekend!

**Comment by titouanmathis** [comment]
Thanks for the report, I'll have a look on Monday 👍
