### ISSUE TITLE
"icon" reference is missing in the Accordion component

### ISSUE THREAD

**Issue by w-jerome** [studiometa/js-toolkit#93]
When I set up an [accordion with a transition](https://js-toolkit.meta.fr/components/Accordion.html#with-transitions), I have a `warning` in my console :

`[AccordionItem] The "icon" ref is not defined in the class configuration. Did you forgot to define it?`

https://github.com/studiometa/js-toolkit/blob/0e3c8f94d4d1d0f29e782c7f4f760b410aec0736/src/components/Accordion/AccordionItem.js#L51

**Comment by titouanmathis** [comment]
This is by design, see #82.

Did the documentation misled you? We might need to update it as you are not the first to report this as an issue.
